# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: astarteplatform/msghub/astarte_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from astarteplatform.msghub import astarte_type_pb2 as astarteplatform_dot_msghub_dot_astarte__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,astarteplatform/msghub/astarte_message.proto\x12\x16\x61starteplatform.msghub\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)astarteplatform/msghub/astarte_type.proto\"\xf0\x01\n\x0e\x41starteMessage\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12?\n\x0c\x61starte_data\x18\x03 \x01(\x0b\x32\'.astarteplatform.msghub.AstarteDataTypeH\x00\x12=\n\rastarte_unset\x18\x04 \x01(\x0b\x32$.astarteplatform.msghub.AstarteUnsetH\x00\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\t\n\x07payload\"\x0e\n\x0c\x41starteUnsetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astarteplatform.msghub.astarte_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ASTARTEMESSAGE']._serialized_start=149
  _globals['_ASTARTEMESSAGE']._serialized_end=389
  _globals['_ASTARTEUNSET']._serialized_start=391
  _globals['_ASTARTEUNSET']._serialized_end=405
# @@protoc_insertion_point(module_scope)
