# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: astarteplatform/msghub/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#astarteplatform/msghub/config.proto\x12\x16\x61starteplatform.msghub\x1a\x1bgoogle/protobuf/empty.proto\"\xd9\x01\n\rConfigMessage\x12\r\n\x05realm\x18\x01 \x01(\t\x12\x16\n\tdevice_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1f\n\x12\x63redentials_secret\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x0bpairing_url\x18\x04 \x01(\t\x12\x1a\n\rpairing_token\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x10grpc_socket_port\x18\x06 \x01(\rB\x0c\n\n_device_idB\x15\n\x13_credentials_secretB\x10\n\x0e_pairing_token2^\n\x10MessageHubConfig\x12J\n\tSetConfig\x12%.astarteplatform.msghub.ConfigMessage\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astarteplatform.msghub.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONFIGMESSAGE']._serialized_start=93
  _globals['_CONFIGMESSAGE']._serialized_end=310
  _globals['_MESSAGEHUBCONFIG']._serialized_start=312
  _globals['_MESSAGEHUBCONFIG']._serialized_end=406
# @@protoc_insertion_point(module_scope)
