# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Astarte device SDK Python"
SPDX-PackageDownloadLocation = "https://github.com/astarte-platform/astarte-device-sdk-python"

[[annotations]]
path = "docs/index.rst"
precedence = "aggregate"
SPDX-FileCopyrightText = "SECO Mind Srl"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "examples/**/interfaces/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "SECO Mind Srl"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "e2etest/interfaces/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "SECO Mind Srl"
SPDX-License-Identifier = "CC0-1.0"
