name: Code Quality Checks
on: [pull_request]

jobs:
  static:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 --version
        python3 -m pip install --upgrade pip
        python3 -m pip install -e .
        python3 -m pip install black==23.1.0 pylint==v2.16.2
    - name: Format check
      run: python3 -m black -l 100 --diff --check $(git ls-files 'astarte')
    - name: Linting
      run: python3 -m pylint $(git ls-files 'astarte')
